# Generated by Django 5.0.6 on 2026-07-16 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='family.family'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('family', 'name')},
        ),
    ]
