version: '3.8'

services:
  mongo:
    image: mongo:8
    container_name: gharkobill_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: gharkobill_postgres
    environment:
      POSTGRES_DB: gharkobill
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: gharkobill_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mongo_data:
  postgres_data:
