# Generated by Django 5.0.6 on 2026-07-16 09:09

import apps.warranties.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('purchase_date', models.DateField()),
                ('warranty_expiry', models.DateField()),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to=apps.warranties.models.receipt_upload_path)),
                ('notes', models.TextField(blank=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='family.family')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranties_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['warranty_expiry'],
            },
        ),
    ]
