# Generated by Django 5.0.6 on 2026-07-16 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billproof',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='bills.bill'),
        ),
        migrations.AddField(
            model_name='billproof',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_proofs_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billproof',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_proofs_verified', to=settings.AUTH_USER_MODEL),
        ),
    ]
