# Generated by Django 5.0.6 on 2026-07-16 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0002_initial'),
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='family.family'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('family', 'category', 'month')},
        ),
    ]
