# Generated by Django 5.0.6 on 2026-07-16 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='admin',
            field=models.ForeignKey(help_text='The user who created and manages the family account.', on_delete=django.db.models.deletion.RESTRICT, related_name='administered_families', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familymember',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='family.family'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='familymember',
            unique_together={('family', 'user')},
        ),
    ]
